all:
  vars:
    ansible_user: vdmitriev
    # TODO: cleanup or move to the group_vars/all depending on the heketi PoC
    heketi_admin_key: "adm1n-k3y"
    heketi_user_key: "us3r-k3y"
  children:
    k8s-cluster:
      children:
        kube-master:
          hosts: &kube-masters
            inw-vm41.rfiserve.net:
            inw-vm43.rfiserve.net:
            inw-vm49.rfiserve.net:
        kube-node:
          hosts: &kube-nodes
            inw-vm52.rfiserve.net:
            inw-vm60.rfiserve.net:
    etcd:
      hosts:
        <<: *kube-masters
    heketi-node:
      vars:
        disk_volume_device_1: "/dev/vdb"
      hosts:
        <<: *kube-nodes