apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: sre
    app: prometheus
  name: sre
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 1
  retention: 2d
  resources:
    requests:
      cpu: 250m
      memory: 400Mi
    limits:
      cpu: 250m
      memory: 1Gi
  ruleSelector:
    matchLabels:
      prometheus: sre
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      team: sre
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: gluster
  version: v2.8.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: sre
    app: prometheus
  name: prometheus-sre
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: sre
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-sre
  namespace: monitoring
  labels:
    prometheus: sre
    app: prometheus
  annotations:
    external-dns.alpha.kubernetes.io/target: ingress-controller.k8s-sbx.rfiserve.net
spec:
  rules:
  - host: prometheus-sre.k8s-sbx.rfiserve.net
    http:
      paths:
      - backend:
          serviceName: prometheus-sre
          servicePort: 9090
