# prometheus service monitor [ ! should be deployed after prometheus operator otherwise will fail ! ]
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-sbx
  labels:
    app: jenkins-sbx
    team: sre
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: jenkins-sbx
  endpoints:
  - path: /prometheus
    port: http
    metricRelabelings:
    - action: drop
      regex: jenkins_node_jenkins_sbx_slave_.*_builds.*
      sourceLabels:
      - __name__
