# prometheus service monitor [ ! should be deployed after prometheus operator otherwise will fail ! ]
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: sre
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web