---
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  environment:
    PATH: '/sbin:/usr/sbin:{{ ansible_env.PATH }}'
  when: ansible_swaptotal_mb > 0
