# Default values for coredns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: "1.4.0"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceType: "LoadBalancer"

# service:
  # 'loadBalancerIP' option will be supported after https://github.com/helm/charts/pull/11281 is merged
  # loadBalancerIP: 172.22.4.129

rbac:
  # If true, create & use RBAC resources
  create: true

# isClusterService specifies whether chart should be deployed as cluster-service or normal k8s app.
isClusterService: false

servers:
- zones:
  - zone: k8s-sbx.rfiserve.net.
  port: 53
  plugins:
  - name: cache
    parameters: 30
  - name: errors
  - name: log
  - name: health
  - name: loop
  - name: reload
  - name: loadbalance
  - name: prometheus
    parameters: :9153
  - name: etcd
    parameters: k8s-sbx.rfiserve.net
    # etcd url equals to the default etcd service name created by etcd operator
    configBlock: |-
      path /skydns
      endpoint http://etcd-cluster-extdns-client:2379
  # uncomment lines below if you plan to handle all DNS requests, zone name above should be changed to "."
  # - name: proxy
  #   parameters: . 172.22.4.55 172.22.4.57

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector:
  node-role.kubernetes.io/master: ""

# expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#toleration-v1-core
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - key: CriticalAddonsOnly
    operator: Exists
