controller:
  image:
    tag: "v0.7-beta.8"

  resources:
   limits:
     cpu: 100m
     memory: 64Mi
   requests:
     cpu: 100m
     memory: 64Mi

  ## Node tolerations for server scheduling to nodes with taints
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - key: CriticalAddonsOnly
    operator: Exists

  ## Node labels for controller pod assignment
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector:
    node-role.kubernetes.io/master: ""

  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: ingress-controller.k8s-sbx.rfiserve.net

  stats:
    enabled: true  

  ## If controller.stats.enabled = true and controller.metrics.enabled = true, Prometheus metrics will be exported
  ##
  metrics:
    enabled: true
