## Details about the image to be pulled.
image:
  tag: v0.5.12

## The DNS provider where the DNS records will be created (options: aws, google, inmemory, azure, rfc2136 )
provider: coredns

# When using the TXT registry, a name that identifies this instance of ExternalDNS
txtOwnerId: "external-dns.vdmitriev-sbx.local"

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector:
  node-role.kubernetes.io/master: ""

## List of node taints to tolerate (requires Kubernetes >= 1.6)
tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
- key: CriticalAddonsOnly
  operator: Exists

## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only )
policy: sync

# Extra environment variables which will be saved in a release-specific secret
# or retrieved via valueFrom.
# extraEnv:
# - name: SECRET_TO_SAVE
#   value: secret_value
# - name: AWS_ACCESS_KEY_ID
#   valueFrom:
#     secretKeyRef:
#       name: existing-secret
#       key: access-key-id
extraEnv:
# etcd url equals to the default etcd service name created by etcd operator
- name: ETCD_URLS
  value: http://etcd-cluster-extdns-client:2379

## CPU and Memory limit and request for external-dns
resources:
 limits:
   memory: 50Mi
   cpu: 10m
 requests:
   memory: 50Mi
   cpu: 10m

rbac:
  ## If true, create & use RBAC resources
  ##
  create: true
